import {StyleSheet} from 'react-native';
export const styles = StyleSheet.create({
  textStyle: {
    marginTop: '25%',
    fontSize: 80,
    fontStyle: 'italic',
    fontWeight: 'bold',
    textDecorationLine: 'underline',
    textAlign: 'center',
    color: '#fff',
  },
  button: {
    height: 45,
    width: 140,
    backgroundColor: '#69C730',
    borderRadius: 5,
  },
  largeText: {
    color: '#69C730',
    // fontWeight: '200',
    fontSize: 25,
    letterSpacing: 1,
    textAlign: 'center',
    alignSelf: 'center',
    padding: 6,
    margin: 6,
  },

  smallText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 16,
    letterSpacing: 1.5,
    textAlign: 'center',
    alignSelf: 'center',
    padding: 6,
    margin: 6,
  },
  textColor: {color: '#fff', fontSize: 17},
  decrement: {
    backgroundColor: '#69C730',
    width: '25%',
    height: 48,
    borderWidth: 0.5,
    borderColor: 'gray',
  },
  increment: {
    backgroundColor: '#69C730',
    width: '25%',
    height: 48,
  },
  inputText: {
    color: 'lightgreen',
    fontSize: 16,
    top: 14,
    left: 4,
  },
  input: {
    margin: 10,
    width: '100%',
    alignSelf: 'center',
    height: 40,
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderLeftWidth: 0,
    padding: 0,
    borderColor: '#fff',
    borderWidth: 1,
    color: '#fff',
    fontSize: 17,
  },
  child: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'space-evenly',
    //  margin: '10%',
  },
  rowDesign: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 5,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 10,
  },

  rowButtonDesign: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    // marginHorizontal: 5,
    backgroundColor: '#FFFFFF',
    height: 48,
  },
  image: {
    flex: 1,
    resizeMode: 'cover',
    justifyContent: 'center',
  },
});
